global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alartmanager:9093

scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - sysops-cadvisor:8080
- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
  - targets:
    - sysops-prometheus:9090