name: Deployment
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODEJS_APP_NAME: sysops-nodejs-app

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push nodejs app image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        uses: ./.github/actions/BuildPushImage
        with:
          image-name: ${{ env.NODEJS_APP_NAME }}
  
  testing:
    needs: build_and_push_image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull and testing
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Set up Docker CLI
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          docker pull $DOCKER_USERNAME/${{ env.NODEJS_APP_NAME }}:$COMMIT_SHA 
          docker tag ${{ env.NODEJS_APP_NAME }}:$COMMIT_SHA ${{ env.NODEJS_APP_NAME }}:v1
          docker compose up -d
          sleep 15
          docker exec -T ${{ env.NODEJS_APP_NAME }} npm run test
